package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.common.internal.safeparcel.b;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public final class zzatb extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzatb> CREATOR = new zzata();
    private final ApplicationInfo applicationInfo;
    private final int versionCode;
    private final zzazn zzbpn;
    private final zzvs zzbpo;
    private final float zzbsd;
    private final String zzbut;
    private final String zzcjn;
    private final boolean zzdmu;
    private final zzaeh zzdoe;
    private final List<String> zzdof;
    private final int zzdqi;
    private final int zzdqj;
    private final Bundle zzduc;
    private final zzvl zzdud;
    private final PackageInfo zzdue;
    private final String zzduf;
    private final String zzdug;
    private final Bundle zzduh;
    private final int zzdui;
    private final Bundle zzduj;
    private final boolean zzduk;
    private final String zzdul;
    private final long zzdum;
    private final String zzdun;
    private final List<String> zzduo;
    private final String zzdup;
    private final List<String> zzduq;
    private final long zzdur;
    private final String zzdus;
    private final float zzdut;
    private final int zzduu;
    private final int zzduv;
    private final boolean zzduw;
    private final String zzdux;
    private final boolean zzduy;
    private final String zzduz;
    private final int zzdva;
    private final Bundle zzdvb;
    private final String zzdvc;
    private final zzzi zzdvd;
    private final boolean zzdve;
    private final Bundle zzdvf;
    private final String zzdvg;
    private final String zzdvh;
    private final String zzdvi;
    private final boolean zzdvj;
    private final List<Integer> zzdvk;
    private final String zzdvl;
    private final List<String> zzdvm;
    private final int zzdvn;
    private final boolean zzdvo;
    private final boolean zzdvp;
    private final boolean zzdvq;
    private final ArrayList<String> zzdvr;
    private final String zzdvs;
    private final zzajt zzdvt;
    private final String zzdvu;
    private final Bundle zzdvv;

    zzatb(int i, Bundle bundle, zzvl zzvl, zzvs zzvs, String str, ApplicationInfo applicationInfo2, PackageInfo packageInfo, String str2, String str3, String str4, zzazn zzazn, Bundle bundle2, int i2, List<String> list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List<String> list2, String str7, zzaeh zzaeh, List<String> list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzzi zzzi, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List<Integer> list4, String str15, List<String> list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList<String> arrayList, String str16, zzajt zzajt, String str17, Bundle bundle6) {
        List<String> list6;
        List<String> list7;
        this.versionCode = i;
        this.zzduc = bundle;
        this.zzdud = zzvl;
        this.zzbpo = zzvs;
        this.zzbut = str;
        this.applicationInfo = applicationInfo2;
        this.zzdue = packageInfo;
        this.zzduf = str2;
        this.zzdug = str3;
        this.zzcjn = str4;
        this.zzbpn = zzazn;
        this.zzduh = bundle2;
        this.zzdui = i2;
        this.zzdof = list;
        if (list3 == null) {
            list6 = Collections.emptyList();
        } else {
            list6 = Collections.unmodifiableList(list3);
        }
        this.zzduq = list6;
        this.zzduj = bundle3;
        this.zzduk = z;
        this.zzdqi = i3;
        this.zzdqj = i4;
        this.zzbsd = f;
        this.zzdul = str5;
        this.zzdum = j;
        this.zzdun = str6;
        if (list2 == null) {
            list7 = Collections.emptyList();
        } else {
            list7 = Collections.unmodifiableList(list2);
        }
        this.zzduo = list7;
        this.zzdup = str7;
        this.zzdoe = zzaeh;
        this.zzdur = j2;
        this.zzdus = str8;
        this.zzdut = f2;
        this.zzduy = z2;
        this.zzduu = i5;
        this.zzduv = i6;
        this.zzduw = z3;
        this.zzdux = str9;
        this.zzduz = str10;
        this.zzdmu = z4;
        this.zzdva = i7;
        this.zzdvb = bundle4;
        this.zzdvc = str11;
        this.zzdvd = zzzi;
        this.zzdve = z5;
        this.zzdvf = bundle5;
        this.zzdvg = str12;
        this.zzdvh = str13;
        this.zzdvi = str14;
        this.zzdvj = z6;
        this.zzdvk = list4;
        this.zzdvl = str15;
        this.zzdvm = list5;
        this.zzdvn = i8;
        this.zzdvo = z7;
        this.zzdvp = z8;
        this.zzdvq = z9;
        this.zzdvr = arrayList;
        this.zzdvs = str16;
        this.zzdvt = zzajt;
        this.zzdvu = str17;
        this.zzdvv = bundle6;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        int a = b.a(parcel);
        b.k(parcel, 1, this.versionCode);
        b.e(parcel, 2, this.zzduc, false);
        b.q(parcel, 3, this.zzdud, i, false);
        b.q(parcel, 4, this.zzbpo, i, false);
        b.r(parcel, 5, this.zzbut, false);
        b.q(parcel, 6, this.applicationInfo, i, false);
        b.q(parcel, 7, this.zzdue, i, false);
        b.r(parcel, 8, this.zzduf, false);
        b.r(parcel, 9, this.zzdug, false);
        b.r(parcel, 10, this.zzcjn, false);
        b.q(parcel, 11, this.zzbpn, i, false);
        b.e(parcel, 12, this.zzduh, false);
        b.k(parcel, 13, this.zzdui);
        b.t(parcel, 14, this.zzdof, false);
        b.e(parcel, 15, this.zzduj, false);
        b.c(parcel, 16, this.zzduk);
        b.k(parcel, 18, this.zzdqi);
        b.k(parcel, 19, this.zzdqj);
        b.h(parcel, 20, this.zzbsd);
        b.r(parcel, 21, this.zzdul, false);
        b.n(parcel, 25, this.zzdum);
        b.r(parcel, 26, this.zzdun, false);
        b.t(parcel, 27, this.zzduo, false);
        b.r(parcel, 28, this.zzdup, false);
        b.q(parcel, 29, this.zzdoe, i, false);
        b.t(parcel, 30, this.zzduq, false);
        b.n(parcel, 31, this.zzdur);
        b.r(parcel, 33, this.zzdus, false);
        b.h(parcel, 34, this.zzdut);
        b.k(parcel, 35, this.zzduu);
        b.k(parcel, 36, this.zzduv);
        b.c(parcel, 37, this.zzduw);
        b.r(parcel, 39, this.zzdux, false);
        b.c(parcel, 40, this.zzduy);
        b.r(parcel, 41, this.zzduz, false);
        b.c(parcel, 42, this.zzdmu);
        b.k(parcel, 43, this.zzdva);
        b.e(parcel, 44, this.zzdvb, false);
        b.r(parcel, 45, this.zzdvc, false);
        b.q(parcel, 46, this.zzdvd, i, false);
        b.c(parcel, 47, this.zzdve);
        b.e(parcel, 48, this.zzdvf, false);
        b.r(parcel, 49, this.zzdvg, false);
        b.r(parcel, 50, this.zzdvh, false);
        b.r(parcel, 51, this.zzdvi, false);
        b.c(parcel, 52, this.zzdvj);
        b.l(parcel, 53, this.zzdvk, false);
        b.r(parcel, 54, this.zzdvl, false);
        b.t(parcel, 55, this.zzdvm, false);
        b.k(parcel, 56, this.zzdvn);
        b.c(parcel, 57, this.zzdvo);
        b.c(parcel, 58, this.zzdvp);
        b.c(parcel, 59, this.zzdvq);
        b.t(parcel, 60, this.zzdvr, false);
        b.r(parcel, 61, this.zzdvs, false);
        b.q(parcel, 63, this.zzdvt, i, false);
        b.r(parcel, 64, this.zzdvu, false);
        b.e(parcel, 65, this.zzdvv, false);
        b.b(parcel, a);
    }
}
