package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.facebook.ads.AdError;
import com.google.android.gms.internal.measurement.zzen;
import com.google.android.gms.internal.measurement.zzex;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import org.apache.http.HttpStatus;

public final class v2 {
    public static final u2<Long> A = b("measurement.upload.initial_upload_delay_time", 15000L, 15000L, k0.a);
    public static final u2<Boolean> A0;
    public static final u2<Long> B = b("measurement.upload.retry_time", 1800000L, 1800000L, l0.a);
    public static final u2<Boolean> B0;
    public static final u2<Integer> C = b("measurement.upload.retry_count", 6, 6, m0.a);
    public static final u2<Long> D = b("measurement.upload.max_queue_time", 2419200000L, 2419200000L, n0.a);
    public static final u2<Integer> E = b("measurement.lifetimevalue.max_currency_tracked", 4, 4, o0.a);
    public static final u2<Integer> F;
    public static final u2<Integer> G = b("measurement.upload.max_public_user_properties", 25, 25, null);
    public static final u2<Integer> H;
    public static final u2<Integer> I = b("measurement.upload.max_public_event_params", 25, 25, null);
    public static final u2<Long> J = b("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, r0.a);
    public static final u2<Boolean> K;
    public static final u2<String> L = b("measurement.test.string_flag", "---", "---", t0.a);
    public static final u2<Long> M = b("measurement.test.long_flag", -1L, -1L, u0.a);
    public static final u2<Integer> N = b("measurement.test.int_flag", -2, -2, v0.a);
    public static final u2<Double> O;
    public static final u2<Integer> P = b("measurement.experiment.max_ids", 50, 50, x0.a);
    public static final u2<Integer> Q = b("measurement.max_bundles_per_iteration", 100, 100, y0.a);
    public static final u2<Long> R = b("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, a1.a);
    public static final u2<Boolean> S;
    public static final u2<Boolean> T;
    public static final u2<Boolean> U;
    public static final u2<Boolean> V;
    public static final u2<Boolean> W;
    public static final u2<Boolean> X;
    public static final u2<Boolean> Y;
    public static final u2<Boolean> Z;
    private static final List<u2<?>> a = Collections.synchronizedList(new ArrayList());
    public static final u2<Boolean> a0;
    public static final u2<Long> b = b("measurement.ad_id_cache_time", 10000L, 10000L, s.a);
    public static final u2<Boolean> b0;
    public static final u2<Long> c = b("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, e0.a);
    public static final u2<Boolean> c0;
    public static final u2<Long> d = b("measurement.config.cache_time", 86400000L, 3600000L, p0.a);
    public static final u2<Boolean> d0;
    public static final u2<String> e = b("measurement.config.url_scheme", "https", "https", b1.a);
    public static final u2<Boolean> e0;
    public static final u2<String> f = b("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", m1.a);
    public static final u2<Boolean> f0;
    public static final u2<Integer> g = b("measurement.upload.max_bundles", 100, 100, x1.a);
    public static final u2<Boolean> g0;
    public static final u2<Integer> h = b("measurement.upload.max_batch_size", 65536, 65536, j2.a);
    public static final u2<Boolean> h0;
    public static final u2<Integer> i = b("measurement.upload.max_bundle_size", 65536, 65536, q2.a);
    public static final u2<Boolean> i0;
    public static final u2<Integer> j;
    public static final u2<Boolean> j0;
    public static final u2<Integer> k = b("measurement.upload.max_events_per_day", 100000, 100000, s2.a);
    public static final u2<Boolean> k0;
    public static final u2<Integer> l;
    public static final u2<Boolean> l0;
    public static final u2<Integer> m = b("measurement.upload.max_public_events_per_day", 50000, 50000, u.a);
    public static final u2<Boolean> m0;
    public static final u2<Integer> n = b("measurement.upload.max_conversions_per_day", 10000, 10000, v.a);
    public static final u2<Boolean> n0;
    public static final u2<Integer> o = b("measurement.upload.max_realtime_events_per_day", 10, 10, w.a);
    public static final u2<Boolean> o0;
    public static final u2<Integer> p = b("measurement.store.max_stored_events_per_app", 100000, 100000, x.a);
    public static final u2<Boolean> p0;
    public static final u2<String> q = b("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", z.a);
    public static final u2<Boolean> q0;
    public static final u2<Long> r = b("measurement.upload.backoff_period", 43200000L, 43200000L, a0.a);
    public static final u2<Boolean> r0;
    public static final u2<Long> s = b("measurement.upload.window_interval", 3600000L, 3600000L, b0.a);
    public static final u2<Boolean> s0;
    public static final u2<Long> t = b("measurement.upload.interval", 3600000L, 3600000L, c0.a);
    public static final u2<Boolean> t0;
    public static final u2<Long> u = b("measurement.upload.realtime_upload_interval", 10000L, 10000L, d0.a);
    public static final u2<Boolean> u0;
    public static final u2<Long> v = b("measurement.upload.debug_upload_interval", 1000L, 1000L, f0.a);
    public static final u2<Boolean> v0;
    public static final u2<Long> w = b("measurement.upload.minimum_delay", 500L, 500L, g0.a);
    public static final u2<Boolean> w0;
    public static final u2<Long> x = b("measurement.alarm_manager.minimum_interval", 60000L, 60000L, h0.a);
    public static final u2<Boolean> x0;
    public static final u2<Long> y = b("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, i0.a);
    public static final u2<Boolean> y0;
    public static final u2<Long> z = b("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, j0.a);
    public static final u2<Integer> z0 = b("measurement.service.storage_consent_support_version", 203590, 203590, n2.a);

    static {
        Collections.synchronizedSet(new HashSet());
        Integer valueOf = Integer.valueOf((int) AdError.NETWORK_ERROR_CODE);
        j = b("measurement.upload.max_events_per_bundle", valueOf, valueOf, r2.a);
        l = b("measurement.upload.max_error_events_per_day", valueOf, valueOf, t.a);
        Integer valueOf2 = Integer.valueOf((int) HttpStatus.SC_OK);
        F = b("measurement.audience.filter_result_max_count", valueOf2, valueOf2, q0.a);
        Integer valueOf3 = Integer.valueOf((int) HttpStatus.SC_INTERNAL_SERVER_ERROR);
        H = b("measurement.upload.max_event_name_cardinality", valueOf3, valueOf3, null);
        Boolean bool = Boolean.FALSE;
        K = b("measurement.test.boolean_flag", bool, bool, s0.a);
        Double valueOf4 = Double.valueOf(-3.0d);
        O = b("measurement.test.double_flag", valueOf4, valueOf4, w0.a);
        S = b("measurement.validation.internal_limits_internal_event_params", bool, bool, c1.a);
        Boolean bool2 = Boolean.TRUE;
        T = b("measurement.collection.firebase_global_collection_flag_enabled", bool2, bool2, d1.a);
        U = b("measurement.collection.redundant_engagement_removal_enabled", bool, bool, e1.a);
        V = b("measurement.collection.log_event_and_bundle_v2", bool2, bool2, f1.a);
        W = b("measurement.quality.checksum", bool, bool, null);
        X = b("measurement.sdk.dynamite.allow_remote_dynamite3", bool2, bool2, g1.a);
        Y = b("measurement.sdk.collection.validate_param_names_alphabetical", bool2, bool2, h1.a);
        Z = b("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, i1.a);
        a0 = b("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, j1.a);
        b0 = b("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, k1.a);
        c0 = b("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, l1.a);
        d0 = b("measurement.sdk.collection.last_deep_link_referrer2", bool2, bool2, n1.a);
        e0 = b("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, o1.a);
        f0 = b("measurement.sdk.collection.last_gclid_from_referrer2", bool, bool, p1.a);
        g0 = b("measurement.sdk.collection.enable_extend_user_property_size", bool2, bool2, q1.a);
        h0 = b("measurement.upload.file_lock_state_check", bool, bool, r1.a);
        i0 = b("measurement.ga.ga_app_id", bool, bool, s1.a);
        j0 = b("measurement.lifecycle.app_in_background_parameter", bool, bool, t1.a);
        k0 = b("measurement.integration.disable_firebase_instance_id", bool, bool, u1.a);
        l0 = b("measurement.lifecycle.app_backgrounded_engagement", bool, bool, v1.a);
        m0 = b("measurement.collection.service.update_with_analytics_fix", bool, bool, w1.a);
        n0 = b("measurement.service.use_appinfo_modified", bool, bool, y1.a);
        o0 = b("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, z1.a);
        p0 = b("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, b2.a);
        q0 = b("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, c2.a);
        r0 = b("measurement.upload.file_truncate_fix", bool, bool, d2.a);
        s0 = b("measurement.sdk.referrer.delayed_install_referrer_api", bool, bool, e2.a);
        t0 = b("measurement.sdk.screen.disabling_automatic_reporting", bool2, bool2, f2.a);
        u0 = b("measurement.sdk.screen.manual_screen_view_logging", bool2, bool2, g2.a);
        b("measurement.collection.synthetic_data_mitigation", bool, bool, h2.a);
        v0 = b("measurement.androidId.delete_feature", bool2, bool2, i2.a);
        w0 = b("measurement.client.consent_state_v1", bool2, bool2, k2.a);
        x0 = b("measurement.client.3p_consent_state_v1", bool2, bool2, l2.a);
        y0 = b("measurement.service.consent_state_v1_W36", bool2, bool2, m2.a);
        A0 = b("measurement.service.directly_maybe_log_error_events", bool, bool, o2.a);
        B0 = b("measurement.client.safer_resources", bool2, bool2, p2.a);
    }

    public static Map<String, String> a(Context context) {
        zzen zza = zzen.zza(context.getContentResolver(), zzex.zza("com.google.android.gms.measurement"));
        return zza == null ? Collections.emptyMap() : zza.zzb();
    }

    static <V> u2<V> b(String str, V v2, V v3, t2<V> t2Var) {
        u2<V> u2Var = new u2<>(str, v2, v3, t2Var);
        a.add(u2Var);
        return u2Var;
    }
}
